server:
  port: 8082
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
spring:
  datasource:
    username: postgres
    password: 1227
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pdp_fastfood
  jpa:
    show-sql: true
debug: true

